sudo: required
services:
  - docker

before_install:
  - docker build -t janslv/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true janslv/react-test npm test

after_success:
  - docker build -t janslv/multi-client ./client
  - docker build -t janslv/multi-nginx ./nginx
  - docker build -t janslv/multi-server ./server
  - docker build -t janslv/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push janslv/multi-client
  - docker push janslv/multi-nginx
  - docker push janslv/multi-server
  - docker push janslv/multi-worker